# CrowdSec Config
crowdsec_lapi_url: http://localhost:8080/
crowdsec_lapi_key: ${LAPI_KEY}

# Cloudfare Config
cloudfare_api_token: ${CF_TOKEN}
cloudfare_account_id: ${CF_ACC_ID}
cloudfare_zone_id: ${CF_ZONE_ID}

cloudfare_ip_list_name: crowdsec

# Bouncer Config
update_frequency: 10s
action: block
daemon: true